### ISSUE TITLE
Is this the function you intended?

### ISSUE THREAD

**Issue by AlphaDoStar** [ttyy3388/msgbots#3]
I'm not using English cuz' I love Korean XD

디버깅 룸에서 출력하는 메시지가 일정 길이 이상일 때
VIEW ALL 이라고 뜨는 것을 확인했어요.

그런데 일반적으로는 앞부분의 일부를 띄워둔 다음 VIEW ALL을 띄우는 것이
바람직해 보이나, 현재 버전의 경우에서는 맨 뒤를 띄우고 VIEW ALL을 띄우고 있어요.

혹시 이것은 의도한 기능인가요?

자잘한 버그를 발견하는 족족 이슈를 남기어
개발자 님의 귀차니즘을 유도하도록 노력하겠습니다.

좋은 프로그램 감사합니다!

+ U+200B 유니코드를 일정 개수(500) 이상 반복했을 시 전체보기로 띄우도록
만들어주실 수 있나요?

+ Bot List에서 스크립트를 선택하면 에디터가 잠시 하얗게 변하는 현상이 있는데,
확인 부탁드려요. (Dark Theme)

![image](https://user-images.githubusercontent.com/55902220/116852128-bb8d3a00-ac2e-11eb-8aa7-37a5d57885c9.png)

**Comment by ttyy3388** [comment]
Q1) 그런데 일반적으로는 앞부분의 일부를 띄워둔 다음 VIEW ALL을 띄우는 것이
바람직해 보이나, 현재 버전의 경우에서는 맨 뒤를 띄우고 VIEW ALL을 띄우고 있어요.
혹시 이것은 의도한 기능인가요?

+ A1) 1000번째 글자까지 띄우도록 [lblComment.setText(message.substring(1000) + "...");] 코드를 작성했는데 잘못 쓴 거 같습니다. [lblComment.setText(message.substring(0, 1000) + "...");]으로 수정하면 정상작동 할 거 같습니다.

Q2) U+200B 유니코드를 일정 개수(500) 이상 반복했을 시 전체보기로 띄우도록
만들어주실 수 있나요?

+ A2) 저는 카카오톡의 전체보기 기준이 글자 1000자인 줄 알고 적용했으나 최신 카카오톡은 500자라고 해서 500자로 변경할 예정입니다. 그러면 따로 수정할 필요가 없지 않을까 싶습니다.

Q3) Bot List에서 스크립트를 선택하면 에디터가 잠시 하얗게 변하는 현상이 있는데,
확인 부탁드려요. (Dark Theme)

+ A3) 에디터는 웹뷰로 구동됩니다. 추후 프로그램을 전반적으로 리메이크 할 예정인데 그 때 웹뷰 쪽 문제도 해결될 거라 봅니다.

버그 리포트 감사합니다. (*메일을 잘 안 읽다 보니 좀 늦게 확인을 하게 됐네요.)

**Comment by ttyy3388** [comment]
해당 문제는 0.7.0 업데이트로 해결된 것 같아, 이슈를 닫겠습니다.
